# Generated by Django 4.1.5 on 2023-01-16 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='상품 이름')),
                ('content', models.TextField(verbose_name='상품 설명')),
                ('price', models.IntegerField(verbose_name='상품 가격')),
                ('location', models.CharField(max_length=500, verbose_name='상품 거래 희망 위치')),
            ],
            options={
                'db_table': 'shinhan_product',
            },
        ),
    ]
